language: cpp
sudo: required
dist: trusty
git:
  submodules: false
addons:
  apt:
    packages:
      - libpam0g-dev
      - libssl-dev
      - libcurl4-openssl-dev
      - libboost-filesystem-dev
before_script:
  - git config --global url.git@github.com:.insteadOf https://github.com/
  - git submodule update --init
before_install:
  - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
  - sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
  - sudo apt-get update -qq
  - sudo apt-get install -qq dotnet-dev-1.0.0-preview1-002702
script:
  - ./build.sh
  - ./test.sh
