# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: sudo apt-get install libpam0g-dev libssl-dev libcurl4-openssl-dev
  displayName: 'apt-get dependencies'

- script: |
    ./build.sh
  displayName: 'Build MMI'
