# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- checkout: self
  submodules: recursive
- script: sudo apt-get install libpam0g-dev libssl-dev libcurl4-openssl-dev
  displayName: 'apt-get dependencies'

- task: ShellScript@2
  inputs:
    scriptPath: build.sh
  displayName: 'Build MMI'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'release'
    targetPath: src/Microsoft.Management.Infrastructure/bin/Microsoft.Management.Infrastructure.dll

- task: ShellScript@2
  inputs:
    scriptPath: test.sh
  displayName: 'Execute Tests'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/*TestResults.trx'

