name: MMI-$(Build.BuildId)
trigger:
  branches:
    include:
    - master
    - release*
pr:
  branches:
    include:
    - master
    - release*

jobs:

- job: build_MMI
  displayName: Build MMI
  pool:
      vmImage: 'ubuntu-latest'
  steps:
    - template: templates/build.yml

- template: templates/compliance.yml
